sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'tag'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Timestamp'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Timestamp'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Timestamp'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Value'. (207)")
[SQL: 
            SELECT Timestamp, Value
            FROM PI_REPLICATION.dbo.Summary_Daily_AVG_TC_PEM_Melting_1
            WHERE tag = 'SC_COV_TOP_VOLTS'
            AND Timestamp BETWEEN '2024-01-01 00:00:00' AND '2024-11-03 00:00:00'
            ORDER BY Timestamp
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
